name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Docker
        uses: docker://docker:stable
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and test
        run: |
          mvn clean test
          mvn sonar:sonar \
                      -Dsonar.projectKey=${{secrets.PROJECT_KEY }}\
                      -Dsonar.organization=${{secrets.SONAR_ORG }} \
                      -Dsonar.host.url=${{secrets.SONAR_URL }} \
                      -Dsonar.login=${{secrets.SONAR_TOKEN }}
      - name: Post to a Slack channel
        if: ${{ job.status == 'failure' }}
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "🚨☠️ Tests are failing! ☠️🚨"
            			}
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Repo:*\n<https://github.com/${{ github.repository }}|${{ github.repository }} >"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Workflow Run:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} | Workflow >"
            				}
            			]
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post to a Slack channel
        if: ${{ job.status == 'success' }}
        id: success-slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "🎉🎉🎉 All tests passed! 🎉🎉🎉"
            			}
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Repo:*\n<https://github.com/${{ github.repository }}|${{ github.repository }} >"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Workflow Run:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} | Workflow >"
            				}
            			]
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}